title: WhoBrokeTheBuild's Development Blog
github_username:  WhoBrokeTheBuild

author: Stephen Lane-Walsh

description: |
  <a href="/blog.html">Blog</a>

markdown: kramdown
theme: jekyll-theme-minimal

include: ['_pages', '_game-engine', '_programming']

collections:
  pages:
    output: true
    permalink: /:title:output_ext
  game-engine:
    output: true
    permalink: /:collection/:title:output_ext
  programming:
    output: true
    permalink: /:collection/:title:output_ext